name: Build and Save Docker Image on ARM64

on:
  push:
    branches:
      - '*' # Or specify branches like 'main'

jobs:
  docker-arm64:
    runs-on: ubuntu-22.04-arm

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set image name
        run: echo "IMG_NAME=web-push-notification-next-app" >> $GITHUB_ENV
    
      - name: Populate env
        run: echo "${{ secrets.BASE64_ENV }}" | base64 -w 0 -d > .env

      - name: Build Docker image (no push)
        run: |
          docker build -t $IMG_NAME:latest .

      - name: Save Docker image to tar file
        run: |
          docker save -o $IMG_NAME.tar $IMG_NAME:latest

    #   - name: Upload Docker image artifact
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: docker-image-${{ env.IMG_NAME }}
    #       path: ${{ env.IMG_NAME }}.tar
      - name: Create Release
        id: create_release
        uses: comnoco/create-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: latest
          release_name: Release Latest ARM64 image
          draft: false
          prerelease: false
