name: Build and Save Docker Image

on:
  push:
    branches:
      - '*' # Or specify branches like 'main'

jobs:
  docker-amd64:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set image name
        run: echo "IMG_NAME=web-push-notification-next-app" >> $GITHUB_ENV

      - name: Build Docker image (no push)
        run: |
          docker build -t $IMG_NAME:latest .

      - name: Save Docker image to tar file
        run: |
          docker save -o $IMG_NAME.tar $IMG_NAME:latest

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image-${{ env.IMG_NAME }}
          path: ${{ env.IMG_NAME }}.tar
